id: P006803
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24128
  title: རྟགས་བསྡུ་བའི་གཞུང་འགྲེལ
  author: ''
  volumes:
    468fe4dc66314f4aa97acd7fdd1afeec:
      image_group_id: I1CZ976
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
